app = "videohash-indexer"
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[services.concurrency]
hard_limit = 10000
soft_limit = 500

[[vm]]
memory = '8gb'
cpu_kind = 'shared'
cpus = 8

[env]
  GOOGLE_CLOUD_PROJECT = "hot-or-not-feed-intelligence"
