app = "videohash-indexer"
primary_region = "sin"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
size = "shared-cpu-2x"
memory = "2gb"

[env]
  GOOGLE_CLOUD_PROJECT = "hot-or-not-feed-intelligence"
